### PR TITLE
Add support for Prometheus metrics as source of scaling

### PR DESCRIPTION
**Pull request by alexander-falca**
## Description
Add support for Prometheus metrics as source of scaling

## How Has This Been Tested?
Tested locally using `mage operator:test` 
Tested on EKS cluster, running operator locally `mage operator:run` and pointing to K8S API server 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

Note: Kubernetes pod autoscaler source code: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go

### CODE REVIEW

**Comment by alexander-falca** [comment]
@amuraru thanks for feedback. Agree on updating project structure. Pushed a new commit with updates.

**Comment by amuraru** [comment]
hi @alexander-falca - thanks - tried to checkout this PR but cannot see the latest changes.
Did you push the changes?

**Comment by alexander-falca** [comment]
hi @amuraru Yes, pushed changes 3 days ago here: https://github.com/alexander-falca/kratos/commit/eff96c1f18789c457ea9de52ec0bd3895fa03a5f 

Let me check why it's not reflected in PR

**Comment by alexander-falca** [comment]
@amuraru I forked repo and recreated PR, https://github.com/adobe/kratos/pull/5 
It seems that issue was related to this repo visibility, changed from private to public last week, while my fork was private

**Comment by alexander-falca** [comment]
Closing in favour of #5

**Pull request closed without merging**
